apiVersion: v1
kind: Service
metadata:
  namespace: nemesys-demo
  name: pgadmin-service
spec:
  type: NodePort
  ports:
    - port: 30000
      targetPort: 80
  selector:
    app: pgadmin-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nemesys-demo
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin-pod
  template:
    metadata:
      labels:
        app: pgadmin-pod
    spec:
      containers:
        - name: pgadmin-container
          image: dpage/pgadmin4
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
                memory: "50Mi"
                cpu: "100m"
            limits:
                memory: "5024Mi"
                cpu: "10000m"           
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: bruno@dcmaster.com.br
            - name: PGADMIN_DEFAULT_PASSWORD
              value: master
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            # - name: tmp
            #   mountPath: /var/lib/pgadmin
      volumes:  
      - name: pgadmin-config
        configMap:
          name: pgadmin-config           
      # - name: tmp
      #   hostPath:
      #     path: /home/brunoaurelio/Projetos/Pessoal/PJ_BI_ROBOPYTHON_BASE/base