#!/bin/zsh

helm upgrade --cleanup-on-fail \
  --install nemesys-sr oci://registry-1.docker.io/bitnamicharts/schema-registry \
  --namespace nemesys-stream-101 \
  --values configs/schema-registry-values.yaml
  