#!/bin/zsh

helm repo add --force-update spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator

helm upgrade --install spark-operator \
    --namespace spark-operator \
    --create-namespace \
    --values spark-operator-values.yaml \
    spark-operator/spark-operator

