apiVersion: v1
kind: Pod
metadata:
  name: teste
  namespace: nemesys-stream-101
spec:
  initContainers:
    - name: git-clone
      image: alpine/git # Any image with git will do
      args:
        - clone
        - --single-branch
        - --verbose
        - https://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@github.com/nemesysdata/nemesys-demo.git
        - /repo # Put it in the volume
      securityContext:
        runAsUser: 1 # Any non-root user will do. Match to the workload.
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: git-repo
          mountPath: /repo
  containers:
    - name: teste
      image: ghcr.io/nemesysdata/nemesys-runner:main
      command:
        - sleep
        - infinity
      envFrom:
      - secretRef:
          name: demo-secrets
      - configMapRef:
          name: demo-config
      volumeMounts:
          - name: git-repo
            mountPath: /repo
  volumes:
    - name: git-repo
      emptyDir: {}
        