apiVersion: v1
kind: Pod
metadata:
  name: teste
  namespace: nemesys-stream-101
spec:
  containers:
    - name: teste
      image: ubuntu
      command:
        - sleep
        - infinity
      envFrom:
      - secretRef:
          name: demo-secrets
      - configMapRef:
          name: demo-config
        