apiVersion: v1
kind: ConfigMap
metadata:
 namespace: nemesys-demo
 name: pgadmin-config
data:
 servers.json: |
   {
       "Servers": {
         "1": {
           "Name": "PostgreSQL DB",
           "Group": "Servers",
           "Port": 5432,
           "Host": "postgres",
           "Username": "postgresadmin",
           "Password": "admin123",
           "MaintenanceDB": "postgres"
         }
       }
   }  