apiVersion: v1
kind: Service
metadata:
  namespace: nemesys-demo
  name: postgres
  labels:
    app: postgres  
spec:
  type: LoadBalancer
  ports:
   - port: 5432
  selector:
   app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nemesys-demo
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11.5
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
                memory: "256Mi"
                cpu: "200m"
            limits:
                memory: "5024Mi"
                cpu: "10000m"          
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          # livenessProbe:
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   exec:
          #     command:
          #       - /bin/sh
          #       - -c
          #       - "pg_isready -U kong && psql -d kong -U kong -c \"SELECT 1=1\""
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: nemesys-demo-pv-claim